#ifndef ERROR_PARSER_H_INCLUDED
#define ERROR_PARSER_H_INCLUDED

void ErrorParser(const int ErrorCode);

enum ErrorCodes
{
    SDL_INITIALISATION_ERROR = -10,
    SDL_WINDOW_CREATION_FAILURE,
    SDL_RENDERER_CREATION_FAILURE,
    SDL_TEXTURE_CREATION_FAILURE,
    VISUALIZER_ARRAY_ALLOCATION_FAILURE,
    INCORRECT_DIMENSION_VALUE,
    INCORRECT_TEST_NUMBER_VALUE,
    MODULE_SUCCESS = 0, 
};

#endif