#ifndef ERROR_PARSER_H_INCLUDED
#define ERROR_PARSER_H_INCLUDED

void ErrorParser(const int ErrorCode);

enum ErrorCodes
{
    SDL_INITIALISATION_ERROR = -20,
    SDL_WINDOW_CREATION_FAILURE,
    SDL_RENDERER_CREATION_FAILURE,
    SDL_TEXTURE_CREATION_FAILURE,
    VISUALIZER_ARRAY_ALLOCATION_FAILURE,
    INCORRECT_DIMENSION_VALUE,
    INCORRECT_TEST_NUMBER_VALUE,
    PARSER_UNKNOWN_COMMAND,
    PARSER_MISSING_ARGUMENT,
    UNKNOWN_PARSER_FAILURE,
    FP_DATA_NULL,
    FP_INFO_NULL,
    FP_PLOT_RAW_NULL,
    FP_PLOT_OPTIMIZED_NULL,
    ZERO_TEST_NUMBER,
    ZERO_CPU_FREQUENCY,
    SYSTEM_FUNCTION_CALL_FAILURE,
    MODULE_SUCCESS = 0, 
};

#endif